config/routes.rb
Jsoner::Application.routes.draw do
  resources :traceroutes

end

app/models/traceroute.rb
class Traceroute < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/traceroutes_controller.rb
class TraceroutesController < ApplicationController
  before_action :set_traceroute, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /traceroutes
  # GET /traceroutes.json
  def index
    @traceroutes = Traceroute.all
  end

  # GET /traceroutes/1
  # GET /traceroutes/1.json
  def show
  end

  # GET /traceroutes/new
  def new
    @traceroute = Traceroute.new
  end

  # GET /traceroutes/1/edit
  def edit
  end

  # POST /traceroutes
  # POST /traceroutes.json
  def create
    @traceroute = Traceroute.new(traceroute_params)

    respond_to do |format|
      if @traceroute.save
        flash[:notice] = 'traceroute  was successfully created.'
        format.html { redirect_to @traceroute, notice: 'Traceroute was successfully created.' }
        format.json { render action: 'show', status: :created, location: @traceroute }
      else
        format.html { render action: 'new' }
        format.json { render json: @traceroute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traceroutes/1
  # PATCH/PUT /traceroutes/1.json
  def update
    respond_to do |format|
      if @traceroute.update(traceroute_params)
        format.html { redirect_to @traceroute, notice: 'Traceroute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @traceroute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traceroutes/1
  # DELETE /traceroutes/1.json
  def destroy
    @traceroute.destroy
    respond_to do |format|
      format.html { redirect_to traceroutes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traceroute
      @traceroute = Traceroute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def traceroute_params
      params.require(:traceroute).permit(:server, :stdout, :stderr, :exit_status, :timestamp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/traceroutes_helper.rb
module TraceroutesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jsoner</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/traceroutes/_form.html.erb
<%= form_for(@traceroute) do |f| %>
  <% if @traceroute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@traceroute.errors.count, "error") %> prohibited this traceroute from being saved:</h2>

      <ul>
      <% @traceroute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :server %><br>
    <%= f.text_field :server %>
  </div>
  <div class="field">
    <%= f.label :stdout %><br>
    <%= f.text_area :stdout %>
  </div>
  <div class="field">
    <%= f.label :stderr %><br>
    <%= f.text_area :stderr %>
  </div>
  <div class="field">
    <%= f.label :exit_status %><br>
    <%= f.text_field :exit_status %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.time_select :timestamp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/traceroutes/edit.html.erb
<h1>Editing traceroute</h1>

<%= render 'form' %>

<%= link_to 'Show', @traceroute %> |
<%= link_to 'Back', traceroutes_path %>

app/views/traceroutes/index.html.erb
<h1>Listing traceroutes</h1>

<table>
  <thead>
    <tr>
      <th>Server</th>
      <th>Stdout</th>
      <th>Stderr</th>
      <th>Exit status</th>
      <th>Timestamp</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @traceroutes.each do |traceroute| %>
      <tr>
        <td><%= traceroute.server %></td>
        <td><%= traceroute.stdout %></td>
        <td><%= traceroute.stderr %></td>
        <td><%= traceroute.exit_status %></td>
        <td><%= traceroute.timestamp %></td>
        <td><%= link_to 'Show', traceroute %></td>
        <td><%= link_to 'Edit', edit_traceroute_path(traceroute) %></td>
        <td><%= link_to 'Destroy', traceroute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Traceroute', new_traceroute_path %>

app/views/traceroutes/new.html.erb
<h1>New traceroute</h1>

<%= render 'form' %>

<%= link_to 'Back', traceroutes_path %>

app/views/traceroutes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Server:</strong>
  <%= @traceroute.server %>
</p>

<p>
  <strong>Stdout:</strong>
  <%= @traceroute.stdout %>
</p>

<p>
  <strong>Stderr:</strong>
  <%= @traceroute.stderr %>
</p>

<p>
  <strong>Exit status:</strong>
  <%= @traceroute.exit_status %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @traceroute.timestamp %>
</p>

<%= link_to 'Edit', edit_traceroute_path(@traceroute) %> |
<%= link_to 'Back', traceroutes_path %>